### ISSUE TITLE
Text Trimmed in PDF before New Page

### ISSUE THREAD

**Issue by devKshitijJain** [shihabmridha/educative.io-downloader#4]
![Screenshot 2020-03-23 at 7 35 33 PM](https://user-images.githubusercontent.com/13154652/77325024-9943a000-6d3d-11ea-8fc3-c7d4532c331d.png)

**Comment by shihabmridha** [comment]
Is it happening for every page? Did not get a chance of talking a look yet.

**Comment by devKshitijJain** [comment]
Yes for every page.

**Comment by shihabmridha** [comment]
Not sure if it has an easy fix. Noticed similar behavior in the chrome browser as well.
Also, I have pushed a commit updating some formation. You might pull and check if it helps.

**Comment by devKshitijJain** [comment]
I tried same thing. Removing header and putting margin as 0 and sheet size as A4. But didn't help. Still cutting.

**Comment by devKshitijJain** [comment]
Although it looks much better as we can guess the text, but still not a solution. Puppeteer has this issue.

**Comment by devKshitijJain** [comment]
Came across https://github.com/gildas-lormeau/SingleFile this chrome plugin. So when you are on the particular page and click on this extension it will download that page as HTML and will have everything of that page in it. May be you can combine your logic along with this?

**Comment by shihabmridha** [comment]
I do not think that will work for PDF because in general, a single page has a limited height. So, whenever you are going to make PDF of a tall page/content chrome will create multiple pages to fit all the data.

**Comment by devKshitijJain** [comment]
I mean you can add option to get html files instead of pdf.

**Comment by devKshitijJain** [comment]
@shihabmridha can you try this? https://chromedevtools.github.io/devtools-protocol/tot/Page/#method-captureSnapshot mentioned here - https://stackoverflow.com/a/54817983

**Comment by shihabmridha** [comment]
@devKshitijJain Thanks for the suggestions. Will give it a shot.

**Comment by devKshitijJain** [comment]
@shihabmridha hey tried this?

**Comment by shihabmridha** [comment]
@devKshitijJain , Just pushed a commit. Try it out: https://github.com/shihabmridha/educative.io-downloader/commit/8e61266cf6657f6e35923171217115597e633651

**Comment by devKshitijJain** [comment]
@shihabmridha worked amazingly well. Thanks for your efforts :)

Now another part of problem is to download pages with all codes available. Currently it downloads only the language which is selected as default. 

Also if login was skipped, it still continued downloading, it should stop if it encounters "This lesson is not available in preview. Buy now for full access."

**Comment by devKshitijJain** [comment]
So let say if code has two languages available then it will create directory structure as 
Course Name
 - Java
 - Python
and it will have all the files present in those.

**Comment by devKshitijJain** [comment]
Could you also enable this in code. This disables the code editor due to which sometimes the code is not captured completely

`const observer = new MutationObserver(mutations => {
    const containerElements = mutations
        .map(mutation => mutation.target
            .querySelector(".code-container:not(.code-container-disabled)"))
        .filter(containerElement => containerElement);
    containerElements.forEach(containerElement => {
        const newContainerElement = containerElement.cloneNode(true);
        newContainerElement.classList.add("code-container-disabled");
        containerElement.replaceWith(newContainerElement);
    });
});
observer.observe(document.body, { subtree: true, childList: true });`

**Comment by devKshitijJain** [comment]
Idea is to have firstPageWithCode where user can define where the code is and then navigate to that page. Look for code block determine languages available. Store those in array. For Loop on that array and first. navigate to above page, click on the first language tab and then continue with downloading pages, and so on

**Comment by devKshitijJain** [comment]
@shihabmridha we can close this

**Comment by shihabmridha** [comment]
Thanks for the effort.
